jobs:
    include:
        - stage: build and test
          language: node_js
          node_js:
            - '6'
            - '8'
          cache:
            yarn: true
          before_install:
          - curl -o- -L https://yarnpkg.com/install.sh | bash
          - export PATH=$HOME/.yarn/bin:$PATH
          install:
          - yarn
          script:
          - yarn test

deploy:
  provider: heroku
  api_key: c7550b33-816e-4e97-8b90-7c555bf3033d
  run: "echo %%% heroku deployed and release %%%"